services:
  etcd:
    image: bitnami/etcd:3.5.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    networks:
      - apisix-network

  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./conf/conf.yaml:/usr/local/apisix/conf/config.yaml
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./plugins:/usr/local/apisix/plugins
      - ./logs:/usr/local/apisix/logs
    ports:
      - "9080:9080"
      - "9180:9180"
    environment:
      - APISIX_STAND_ALONE=false
      - APISIX_ROUTER_HTTP_STRICT_MATCH=false
    networks:
      - apisix-network
    depends_on:
      - etcd

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    volumes:
      - ./conf/dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      - apisix-network
    depends_on:
      - apisix
      - etcd

  mock-api:
    image: node:18-alpine
    volumes:
      - ./mock-api:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge