services:
  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./conf/conf.yaml:/usr/local/apisix/conf/config.yaml
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./plugins:/usr/local/apisix/plugins
      - ./logs:/usr/local/apisix/logs
    ports:
      - "9080:9080"
      - "9180:9180"
    environment:
      - APISIX_STAND_ALONE=true
      - APISIX_ROUTER_HTTP_STRICT_MATCH=false
    networks:
      - apisix-network
    #restart: on-failure

  apisix-dashboard:
    image: nginx:alpine
    volumes:
      - ./dashboard:/usr/share/nginx/html
    ports:
      - "9000:80"
    networks:
      - apisix-network
    depends_on:
      - apisix

  mock-api:
    image: node:18-alpine
    volumes:
      - ./mock-api:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge